"""Add company action tables with Enum status fields

Revision ID: e58b6ae9516b
Revises: ede520f9effa
Create Date: 2025-11-26 10:21:28.508925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e58b6ae9516b'
down_revision: Union[str, None] = 'ede520f9effa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
