"""Change status fields to Enum type in invitations and requests

Revision ID: ede520f9effa
Revises: c3dbbd087338
Create Date: 2025-11-25 16:09:27.074550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede520f9effa'
down_revision: Union[str, None] = 'c3dbbd087338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_invitations', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED', name='invitationstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('company_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED', name='requeststatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_requests', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED', name='requeststatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('company_invitations', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED', name='invitationstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
